hosts:
    db1:
        ip: 10.111.111.111
        services:
            - db
            - log-proxy
    db2:
        ip: 10.111.111.112
        services:
            - db
            - log-proxy
    jenkins:
        ip: 10.111.111.11
        services:
            - ci
            - log-proxy
    jumper:
        ip: 10.111.111.10
        services:
            - log-proxy
            - teleport-proxy
    observer:
        ip: 10.111.111.12
        services:
            - log-proxy
            - log-server
            - monitoring-gateway
            - monitoring-proxy
    search1:
        ip: 10.111.111.121
        services:
            - log-proxy
            - search
    search2:
        ip: 10.111.111.122
        services:
            - log-proxy
            - search
    search3:
        ip: 10.111.111.123
        services:
            - log-proxy
            - search
    jumper:
        ip: 10.111.111.10
        services:
            - log-proxy
            - teleport-proxy
    web1:
        ip: 10.111.111.101
        services:
            - liferay
            - log-proxy
            - web-server
    web2:
        ip: 10.111.111.102
        services:
            - liferay
            - log-proxy
            - web-server
    web2:
        ip: 10.111.111.102
        services:
            - liferay
            - log-proxy
            - web-server
