development: true
hosts:
    localhost:
        services:
            - antivirus
            - backup
            - ci
            - db
            - liferay
            - log-proxy
            - log-server
            - monitoring-gateway
            - monitoring-proxy
            - monitoring-proxy-db
            - search
            - vault
            - web-server